FORMAT: 1A

# element-ui-plus

# Group Account

## Account [/api/cms/account/]

+ Model (application/json)

    {
        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1Njg2ODUyMDcsImlhdCI6MTUzNzE0OTIwNywidXNlcl9pZCI6MSwib3duZXIiOiJ6d3kifQ.kh2AI8kTo90WRoTr2TSSJhu3Ox8DHsD1fcgJfCqBDwA",
        "id": "1",
        "name": "panhezeng",
        "email": "panhezeng@gmail.com",
        "phone": 11111111111,
        "avatar": "http://dummyimage.com/200x100/50B347/FFF&text=panhezeng",
        "organ": "Pxipyimhkg Nrtgkhy Rpno Ygsls Qfjnhwcr",
         "groups": [
              {
                "id": 1,
                "name": "超级管理员",
                "menu": [
                  {
                    "title": "网站内容管理",
                    "children": [
                      {
                        "title": "公告",
                        "path": "/announcement"
                      },
                      {
                        "title": "轮播",
                        "path": "/banner"
                      },
                      {
                        "title": "推荐栏目",
                        "path": "/web_column"
                      },
                      {
                        "title": "网站介绍",
                        "path": "/about"
                      }
                    ]
                  },
                  {
                    "title": "系统管理",
                    "children": [ 
                      {
                        "title": "CMS角色",
                        "path": "/role"
                      },
                      {
                        "title": "CMS用户",
                        "path": "/user"
                      } 
                    ]
                  }
                ]
              },
              {
                "id": 2,
                "name": "网站内容管理员"
              } 
            ]
    }

### GET

+ Response 200

    [Account][]

## Login [POST /api/cms/login/]

+ Request (application/json)

        {
          "username": "panhezeng",
          "password": "panhezeng"
        }

+ Response 200

    [Account][]
