FORMAT: 1A

# element-ui-plus

# Group Common

## Options [GET /api/cms/options/]

+ Response 200

        {
            "permissions": [{"text": "审核权限", "value": 1000}],
            "resource_type": [
              {
                "text": "课程",
                "value": 1,
                "key":"course"
              }
            ]
        }
        
## Todos [GET /api/cms/todos/]

+ Response 200

        []        
        
# Group Account

## Account [/api/cms/account/]

+ Model (application/json)

        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1Njg2ODUyMDcsImlhdCI6MTUzNzE0OTIwNywidXNlcl9pZCI6MSwib3duZXIiOiJ6d3kifQ.kh2AI8kTo90WRoTr2TSSJhu3Ox8DHsD1fcgJfCqBDwA",
            "id": "1",
            "name": "panhezeng",
            "email": "panhezeng@gmail.com",
            "phone": 11111111111,
            "avatar": "http://dummyimage.com/200x100/50B347/FFF&text=panhezeng",
            "organ": "P Organ",
             "groups": [
                  {
                    "id": 1,
                    "name": "超级管理员",
                    "menus": [
                      {
                        "title": "网站内容管理",
                        "children": [
                          {
                            "title": "公告",
                            "path": "/announcement"
                          },
                          {
                            "title": "轮播",
                            "path": "/banner"
                          },
                          {
                            "title": "推荐栏目",
                            "path": "/web_column"
                          },
                          {
                            "title": "网站介绍",
                            "path": "/about"
                          }
                        ]
                      },
                      {
                        "title": "系统管理",
                        "children": [ 
                          {
                            "title": "CMS角色",
                            "path": "/role"
                          },
                          {
                            "title": "CMS用户",
                            "path": "/user"
                          } 
                        ]
                      }
                    ]
                  },
                  {
                    "id": 2,
                    "name": "网站内容管理员"
                  } 
                ]
        }

### GET

+ Response 200

    [Account][]
    
### PATCH

+ Response 200

    [Account][]    

## Login [POST /api/cms/login/]

+ Request (application/json)

        {
          "username": "panhezeng",
          "password": "panhezeng"
        }

+ Response 200

    [Account][]

# Group Announcement

## Announcement [/api/cms/announcement/{id}/]

+ Parameters
    + id (number) 
    
+ Attributes (object)
    + id: 1 (number)
    + title: title
    + type: 1 (number)
    + top: 1 (number)
    + status: 1 (number)
    + content: content
    + attachment (array)
    + creator: creator
    + created_time: `1980-09-02 00:00:00`
    + updated_time: `1980-09-02 00:00:00`  
    
         
### Retrieve a Announcement [GET]

+ Response 200 (application/json)
    + Attributes (Announcement)
    
### Update a Announcement [PATCH]

+ Response 200 (application/json)
    
## All Announcements [/api/cms/announcement/{?limit,offset,search}]

+ Attributes
    + count: 1 (number)
    + results (array[Announcement])

### Retrieve all Announcements [GET]

+ Parameters
    + limit
    + offset
    + search

+ Response 200 (application/json)
    + Attributes (All Announcements)

## Update Announcements [PATCH /api/cms/announcement/{?ids}]

+ Parameters
    + ids
    
+ Request (application/json)
    + Headers
        
            X-BULK-OPERATION: true
        
+ Response 200 (application/json)
